SELECT CONTENTS.CONTENT_ID AS CONTENT_ID, TITLE, DESCRIPTION, COUNT(*) AS NUMBER_OF_VIEWERS
FROM CONTENTS
JOIN CONTENT_VIEWERS
ON(CONTENTS.CONTENT_ID = CONTENT_VIEWERS.CONTENT_ID)
GROUP BY CONTENTS.CONTENT_ID, TITLE, DESCRIPTION
ORDER BY NUMBER_OF_VIEWERS DESC