SELECT COURSES.COURSE_ID AS COURSE_ID, COURSES.TITLE AS TITLE, COURSES.DESCRIPTION AS DESCRIPTION, PRICE, AVG(RATE) AS RATE
FROM COURSES
JOIN CONTENTS
ON(COURSES.COURSE_ID = CONTENTS.COURSE_ID)
WHERE CREATOR_ID = $1
GROUP BY COURSES.COURSE_ID, COURSES.TITLE, COURSES.DESCRIPTION
ORDER BY RATE