SELECT
    COURSES.COURSE_ID AS COURSE_ID, 
    COURSES.TITLE AS TITLE, 
    COURSES.DESCRIPTION AS DESCRIPTION, 
    COURSES.DATE_OF_CREATION AS DATE_OF_CREATION, 
    PRICE, 
    CREATOR_ID, 
    FULL_NAME AS CREATOR_NAME, 
    AVG(RATE) AS RATE 
FROM COURSES
JOIN USERS
ON(COURSES.CREATOR_ID = USERS.USER_ID)
JOIN CONTENTS
ON(COURSES.COURSE_ID = CONTENTS.COURSE_ID)
WHERE COURSES.COURSE_ID = $1
GROUP BY COURSES.COURSE_ID, COURSES.TITLE, COURSES.DESCRIPTION, COURSES.DATE_OF_CREATION, PRICE, CREATOR_ID, FULL_NAME