SELECT 
    USERS.USER_ID AS USER_ID, 
    FULL_NAME, 
    SECURITY_KEY, 
    DATE_OF_BIRTH, 
    BIO, 
    EMAIL, 
    ADDRESS, 
    GENDER, 
    CREDIT_CARD_ID, 
    BANK_ID, 
    INTERESTS, 
    DATE_OF_JOIN, 
    RANK_POINT 
FROM USERS
JOIN STUDENTS
ON(USERS.USER_ID = STUDENTS.USER_ID)
WHERE USERS.USER_ID = $1