SELECT 
    COMMENT_ID, 
    CONTENT_ID, 
    COMMENTER_ID, 
    FULL_NAME AS COMMENTER_NAME, 
    TRIM(DESCRIPTION) AS DESCRIPTION, 
    TIME::TIME(0) WITH TIME ZONE AS TIME, 
    DATE, 
    RATE::NUMERIC(3, 2) AS RATE
FROM COMMENTS
JOIN USERS
ON(COMMENTS.COMMENTER_ID = USERS.USER_ID)
WHERE CONTENT_ID = $1