SELECT 
    CONTENTS.CONTENT_ID AS CONTENT_ID,
    CONTENTS.DATE_OF_CREATION AS DATE_OF_CREATION, 
    CONTENT_TYPE, 
    RATE, 
    CONTENTS.TITLE AS TITLE, 
    TRIM(CONTENTS.DESCRIPTION) AS DESCRIPTION, 
    CONTENTS.COURSE_ID AS COURSE_ID, 
    COURSES.TITLE AS COURSE_NAME,
    COUNT(USER_ID) AS VIEW_COUNT
FROM CONTENTS
JOIN CONTENT_VIEWERS
ON(CONTENTS.CONTENT_ID = CONTENT_VIEWERS.CONTENT_ID)
JOIN COURSES
ON(CONTENTS.COURSE_ID = COURSES.COURSE_ID)
WHERE CONTENTS.CONTENT_ID = $1
GROUP BY CONTENTS.CONTENT_ID, CONTENTS.DATE_OF_CREATION, CONTENT_TYPE, RATE, CONTENTS.TITLE, CONTENTS.DESCRIPTION, CONTENTS.COURSE_ID, COURSES.TITLE