SELECT FULL_NAME, EMAIL, BIO, AVG(RATE) AS RATE
FROM USERS
JOIN TEACHERS
ON(USERS.USER_ID = TEACHERS.USER_ID)
JOIN COURSES
ON(TEACHERS.USER_ID = COURSES.CREATOR_ID)
JOIN CONTENTS
ON(COURSES.COURSE_ID = CONTENTS.COURSE_ID)
WHERE USERS.USER_ID = $1
GROUP BY FULL_NAME, EMAIL, BIO