SELECT COURSES_2.COURSE_ID AS COURSE_ID, COURSES_2.TITLE AS TITLE, COURSES_2.DESCRIPTION AS DESCRIPTION, PRICE, NUMBER_OF_ENROLLS, AVG(RATE) AS RATE
FROM(
    SELECT COURSES.COURSE_ID AS COURSE_ID, USER_ID, TITLE, DESCRIPTION, PRICE, COUNT(*) AS NUMBER_OF_ENROLLS
    FROM COURSES
    JOIN ENROLLED_COURSES
    ON(COURSES.COURSE_ID = ENROLLED_COURSES.COURSE_ID)
    GROUP BY COURSES.COURSE_ID, USER_ID, TITLE, DESCRIPTION, PRICE
) COURSES_2
JOIN CONTENTS
ON(COURSES_2.COURSE_ID = CONTENTS.COURSE_ID)
WHERE USER_ID = $1
GROUP BY COURSES_2.COURSE_ID, COURSES_2.TITLE, COURSES_2.DESCRIPTION, PRICE, NUMBER_OF_ENROLLS
ORDER BY NUMBER_OF_ENROLLS DESC, RATE DESC