SELECT CONTENTS.CONTENT_ID, DATE_OF_CREATION, CONTENT_TYPE, RATE, TITLE, DESCRIPTION, COURSE_ID, COUNT(USER_ID) AS VIEWER_COUNT
FROM CONTENTS
JOIN CONTENT_VIEWERS
ON(CONTENTS.CONTENT_ID = CONTENT_VIEWERS.CONTENT_ID)
WHERE CONTENTS.CONTENT_ID = $1
GROUP BY CONTENTS.CONTENT_ID, DATE_OF_CREATION, CONTENT_TYPE, RATE, TITLE, DESCRIPTION, COURSE_ID