SELECT 
    USERS.USER_ID AS USER_ID, 
    FULL_NAME, 
    SECURITY_KEY, 
    DATE_OF_BIRTH, 
    TRIM(BIO) AS BIO, 
    EMAIL, 
    USER_TYPE, 
    CREDIT_CARD_ID, 
    BANK_ID, 
    DATE_OF_JOIN, 
    RANK_POINT 
FROM USERS
JOIN STUDENTS
ON(USERS.USER_ID = STUDENTS.USER_ID)
WHERE USERS.USER_ID = $1