CREATE OR REPLACE FUNCTION SUBTRACT(PARAM_CLIENT_ID BIGINT, PARAM_PASSWORD VARCHAR, PARAM_AMOUNT INT)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	SELECTED_CLIENT_ID BIGINT;
	AMOUNT INT;
BEGIN
	SELECT CLIENT_ID INTO SELECTED_CLIENT_ID
	FROM CLIENTS
	WHERE CLIENT_ID = PARAM_CLIENT_ID AND SECURITY_KEY = PARAM_PASSWORD;
	IF SELECTED_CLIENT_ID IS NULL THEN
		RETURN 1; --INVALID CREDENTIALS
	END IF;
	SELECT CREDIT INTO AMOUNT
	FROM CLIENTS
	WHERE CLIENT_ID = PARAM_CLIENT_ID;
	IF PARAM_AMOUNT > AMOUNT THEN
		RETURN 2; --INSUFFICIENT CREDIT
	END IF;
	UPDATE CLIENTS
	SET CREDIT = CREDIT - PARAM_AMOUNT
	WHERE CLIENT_ID = PARAM_CLIENT_ID;
	RETURN 0; --SUCCESS
END;