CREATE OR REPLACE FUNCTION CHECK_STUDENT_ENROLLED(PARAM_USER_ID BIGINT, PARAM_COURSE_ID BIGINT)
RETURNS BOOL
LANGUAGE PLPGSQL
AS
$$
DECLARE
	QUERY_COUNT INT;
BEGIN
	SELECT COUNT(*) INTO QUERY_COUNT
	FROM ENROLLED_COURSES
	WHERE USER_ID = PARAM_USER_ID AND COURSE_ID = PARAM_COURSE_ID;
	IF QUERY_COUNT > 0 THEN
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$;