CREATE OR REPLACE FUNCTION GET_CONTENT_DETAILS(PARAM_CONTENT_ID BIGINT)
RETURNS TABLE(CONTENT_ID BIGINT, DATE_OF_CREATION DATE, CONTENT_TYPE VARCHAR, RATE NUMERIC, TITLE VARCHAR, DESCRIPTION VARCHAR, COURSE_ID BIGINT, COURSE_NAME VARCHAR, VIEW_COUNT BIGINT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		CONTENTS.CONTENT_ID,
		CONTENTS.DATE_OF_CREATION,
		TRIM(CONTENTS.CONTENT_TYPE)::VARCHAR,
		CONTENTS.RATE::NUMERIC(3, 2),
		CONTENTS.TITLE,
		TRIM(CONTENTS.DESCRIPTION)::VARCHAR,
		COURSES.COURSE_ID,
		COURSES.TITLE,
		CONTENTS.VIEW_COUNT
	FROM CONTENTS
	JOIN COURSES
	ON (CONTENTS.COURSE_ID = COURSES.COURSE_ID)
	WHERE CONTENTS.CONTENT_ID = PARAM_CONTENT_ID;
END;
$$;