CREATE OR REPLACE FUNCTION GET_NEW_ANSWER_ID()
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	MAX_ANSWER_ID BIGINT;
	NEW_ANSWER_ID BIGINT;
BEGIN
	SELECT MAX(ANSWER_ID) INTO MAX_ANSWER_ID
	FROM FORUM_ANSWERS;
	IF MAX_ANSWER_ID IS NULL THEN
		RETURN 1;
	ELSE
		FOR I IN 1..MAX_ANSWER_ID LOOP
			SELECT ANSWER_ID INTO NEW_ANSWER_ID
			FROM FORUM_ANSWERS
			WHERE ANSWER_ID = I;
			IF NEW_ANSWER_ID IS NULL THEN
				RETURN I;
			END IF;
		END LOOP;
		RETURN MAX_ANSWER_ID + 1;
	END IF;
END;
$$;