CREATE OR REPLACE FUNCTION GET_NEW_QUESTION_ID()
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	MAX_QUESTION_ID BIGINT;
	NEW_QUESTION_ID BIGINT;
BEGIN
	SELECT MAX(QUESTION_ID) INTO MAX_QUESTION_ID
	FROM FORUM_QUESTIONS;
	IF MAX_QUESTION_ID IS NULL THEN
		RETURN 1;
	ELSE
		FOR I IN 1..MAX_QUESTION_ID LOOP
			SELECT QUESTION_ID INTO NEW_QUESTION_ID
			FROM FORUM_QUESTIONS
			WHERE QUESTION_ID = I;
			IF NEW_QUESTION_ID IS NULL THEN
				RETURN I;
			END IF;
		END LOOP;
		RETURN MAX_QUESTION_ID + 1;
	END IF;
END;
$$;