CREATE OR REPLACE FUNCTION GET_COURSE_REMAIN_CONTENT(PARAM_USER_ID BIGINT, PARAM_COURSE_ID BIGINT)
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	TO_RETURN BIGINT;
BEGIN
	SELECT REMAIN_COUNT INTO TO_RETURN
	FROM COURSE_REMAIN_CONTENTS
	WHERE USER_ID = PARAM_USER_ID AND COURSE_ID = PARAM_COURSE_ID;
	RETURN TO_RETURN;
END;
$$;