CREATE OR REPLACE FUNCTION GET_INDIVIDUAL_QUESTION_RATE(PARAM_USER_ID BIGINT, PARAM_QUESTION_ID BIGINT)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	RATE_VALUE INT;
BEGIN
	SELECT RATE INTO RATE_VALUE
	FROM QUESTION_RATES
	WHERE USER_ID = PARAM_USER_ID AND QUESTION_ID = PARAM_QUESTION_ID;
	RETURN RATE_VALUE;
END;
$$;