CREATE OR REPLACE FUNCTION GET_ANSWERS_BY_TIME_DESC(PARAM_QUESTION_ID BIGINT)
RETURNS TABLE(ANSWER_ID BIGINT, QUESTION_ID BIGINT, ANSWERER_ID BIGINT, ANSWERER_NAME VARCHAR, ANSWER VARCHAR, TIME_OF_ANSWER TIME WITH TIME ZONE, DATE_OF_ANSWER DATE, RATE NUMERIC)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		FORUM_ANSWERS.ANSWER_ID,
		FORUM_ANSWERS.QUESTION_ID,
		FORUM_ANSWERS.ANSWERER_ID,
		USERS.FULL_NAME,
		TRIM(FORUM_ANSWERS.ANSWER)::VARCHAR,
		FORUM_ANSWERS.TIME_OF_ANSWER::TIME(0) WITH TIME ZONE,
		FORUM_ANSWERS.DATE_OF_ANSWER,
		FORUM_ANSWERS.RATE::NUMERIC(3, 1)
	FROM FORUM_ANSWERS
	JOIN USERS
	ON (FORUM_ANSWERS.ANSWERER_ID = USERS.USER_ID)
	WHERE FORUM_ANSWERS.QUESTION_ID = PARAM_QUESTION_ID
	ORDER BY FORUM_ANSWERS.DATE_OF_ANSWER DESC, FORUM_ANSWERS.TIME_OF_ANSWER DESC;
END;
$$;