CREATE OR REPLACE FUNCTION GET_NEW_USER_ID()
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	MAX_USER_ID BIGINT;
	NEW_USER_ID BIGINT;
BEGIN
	SELECT MAX(USER_ID) INTO MAX_USER_ID
	FROM USERS;
	IF MAX_USER_ID IS NULL THEN
		RETURN 1;
	ELSE
		FOR I IN 1..MAX_USER_ID LOOP
			SELECT USER_ID INTO NEW_USER_ID
			FROM USERS
			WHERE USER_ID = I;
			IF NEW_USER_ID IS NULL THEN
				RETURN I;
			END IF;
		END LOOP;
		RETURN MAX_USER_ID + 1;
	END IF;
END;
$$;