CREATE OR REPLACE FUNCTION GET_USER_ID(PARAM_EMAIL VARCHAR, PARAM_PASSWORD VARCHAR, PARAM_STUDENT BOOLEAN)
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	RETURN_USER_ID BIGINT;
BEGIN
	IF PARAM_STUDENT THEN
		SELECT USERS.USER_ID INTO RETURN_USER_ID
		FROM USERS
		JOIN STUDENTS
		ON (USERS.USER_ID = STUDENTS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL AND SECURITY_KEY = PARAM_PASSWORD;
	ELSE
		SELECT USERS.USER_ID INTO RETURN_USER_ID
		FROM USERS
		JOIN TEACHERS
		ON (USERS.USER_ID = TEACHERS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL AND SECURITY_KEY = PARAM_PASSWORD;
	END IF;
	IF RETURN_USER_ID IS NULL THEN
		RETURN_USER_ID := 0;
    END IF;
	RETURN RETURN_USER_ID;
END;
$$