CREATE OR REPLACE FUNCTION GET_COMMENTS_BY_TIME_DESC(PARAM_CONTENT_ID BIGINT)
RETURNS TABLE(COMMENT_ID BIGINT, CONTENT_ID BIGINT, COMMENTER_ID BIGINT, COMMENTER_NAME VARCHAR, DESCRIPTION VARCHAR, TIME_OF_COMMENT TIME WITH TIME ZONE, DATE_OF_COMMENT DATE, RATE NUMERIC)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		COMMENTS.COMMENT_ID,
		COMMENTS.CONTENT_ID,
		COMMENTS.COMMENTER_ID,
		USERS.FULL_NAME,
		TRIM(COMMENTS.DESCRIPTION)::VARCHAR,
		COMMENTS.TIME::TIME(0) WITH TIME ZONE,
		COMMENTS.DATE,
		COMMENTS.RATE::NUMERIC(3, 1)
	FROM COMMENTS
	JOIN USERS
	ON (COMMENTS.COMMENTER_ID = USERS.USER_ID)
	WHERE COMMENTS.CONTENT_ID = PARAM_CONTENT_ID
	ORDER BY COMMENTS.DATE DESC, COMMENTS.TIME DESC;
END;
$$;