CREATE OR REPLACE FUNCTION GET_USER_ID(PARAM_EMAIL VARCHAR, PARAM_SECURITY_KEY VARCHAR, PARAM_TYPE BOOL)
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	RETURN_USER_ID BIGINT;
	USER_SECURITY_KEY VARCHAR;
BEGIN
	IF LENGTH(PARAM_EMAIL) = 0 THEN
		RETURN -1;
	END IF;
	IF PARAM_EMAIL NOT LIKE '%_@_%.___' THEN
		RETURN -2;
	END IF;
	IF LENGTH(PARAM_SECURITY_KEY) < 8 OR LENGTH(PARAM_SECURITY_KEY) > 32 THEN
		RETURN -3;
	END IF;
	IF PARAM_TYPE THEN
		SELECT USERS.USER_ID INTO RETURN_USER_ID
		FROM USERS
		JOIN STUDENTS
		ON(USERS.USER_ID = STUDENTS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL;
	ELSE
		SELECT USERS.USER_ID INTO RETURN_USER_ID
		FROM USERS
		JOIN TEACHERS
		ON(USERS.USER_ID = TEACHERS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL;
	END IF;
	IF RETURN_USER_ID IS NULL THEN
		RETURN -4;
	END IF;
	SELECT SECURITY_KEY INTO USER_SECURITY_KEY
	FROM USERS
	WHERE USER_ID = RETURN_USER_ID;
	IF USER_SECURITY_KEY = PARAM_SECURITY_KEY THEN
		RETURN RETURN_USER_ID;
	ELSE
		RETURN -5;
	END IF;
END;
$$;