CREATE OR REPLACE FUNCTION GET_STUDENT_COURSES_BY_TITLE_ASC(PARAM_USER_ID BIGINT)
RETURNS TABLE(COURSE_ID BIGINT, TITLE VARCHAR, DESCRIPTION VARCHAR, DATE_OF_CREATION DATE, PRICE INT, CREATOR_ID BIGINT, CREATOR_NAME VARCHAR, RATE NUMERIC, ENROLL_COUNT BIGINT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT COURSES.COURSE_ID, COURSES.TITLE, TRIM(COURSES.DESCRIPTION)::VARCHAR, COURSES.DATE_OF_CREATION, COURSES.PRICE, COURSES.CREATOR_ID, USERS.FULL_NAME, COURSES.RATE::NUMERIC(3, 2), COURSES.ENROLL_COUNT
	FROM COURSES
	JOIN ENROLLED_COURSES
	ON(COURSES.COURSE_ID = ENROLLED_COURSES.COURSE_ID)
	JOIN USERS
	ON(COURSES.CREATOR_ID = USERS.USER_ID)
	WHERE ENROLLED_COURSES.USER_ID = PARAM_USER_ID
	ORDER BY COURSES.TITLE ASC;
END;
$$;