CREATE OR REPLACE FUNCTION GET_NEW_CONTENT_ID()
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	MAX_CONTENT_ID BIGINT;
	NEW_CONTENT_ID BIGINT;
BEGIN
	SELECT MAX(CONTENT_ID) INTO MAX_CONTENT_ID
	FROM CONTENTS;
	IF MAX_CONTENT_ID IS NULL THEN
		RETURN 1;
	ELSE
		FOR I IN 1..MAX_CONTENT_ID LOOP
			SELECT CONTENT_ID INTO NEW_CONTENT_ID
			FROM CONTENTS
			WHERE CONTENT_ID = I;
			IF NEW_CONTENT_ID IS NULL THEN
				RETURN I;
			END IF;
		END LOOP;
		RETURN MAX_CONTENT_ID + 1;
	END IF;
END;
$$;