CREATE OR REPLACE FUNCTION GET_INDIVIDUAL_COMMENT_RATE(PARAM_USER_ID BIGINT, PARAM_COMMENT_ID BIGINT)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	RATE_VALUE INT;
BEGIN
	SELECT RATE INTO RATE_VALUE
	FROM COMMENT_RATES
	WHERE USER_ID = PARAM_USER_ID AND COMMENT_ID = PARAM_COMMENT_ID;
	RETURN RATE_VALUE;
END;
$$;