CREATE OR REPLACE FUNCTION GET_TEACHER_DETAILS(PARAM_TEACHER_ID BIGINT)
RETURNS TABLE(USER_ID BIGINT, FULL_NAME VARCHAR, EMAIL VARCHAR, BIO VARCHAR, DATE_OF_BIRTH DATE, DATE_OF_JOIN DATE, RATE NUMERIC, CREDIT INT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		USERS.USER_ID,
		USERS.FULL_NAME,
		USERS.EMAIL,
		TRIM(USERS.BIO)::VARCHAR,
		USERS.DATE_OF_BIRTH,
		TEACHERS.DATE_OF_JOIN,
		TEACHERS.RATE::NUMERIC(3, 2),
		TEACHERS.CREDIT
	FROM USERS
	JOIN TEACHERS
	ON (USERS.USER_ID = TEACHERS.USER_ID)
	WHERE USERS.USER_ID = PARAM_TEACHER_ID;
END;
$$;