CREATE OR REPLACE FUNCTION GET_NEW_COURSE_ID()
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	MAX_COURSE_ID BIGINT;
	NEW_COURSE_ID BIGINT;
BEGIN
	SELECT MAX(COURSE_ID) INTO MAX_COURSE_ID
	FROM COURSES;
	IF MAX_COURSE_ID IS NULL THEN
		RETURN 1;
	ELSE
		FOR I IN 1..MAX_COURSE_ID LOOP
			SELECT COURSE_ID INTO NEW_COURSE_ID
			FROM COURSES
			WHERE COURSE_ID = I;
			IF NEW_COURSE_ID IS NULL THEN
				RETURN I;
			END IF;
		END LOOP;
		RETURN MAX_COURSE_ID + 1;
	END IF;
END;
$$;