CREATE OR REPLACE FUNCTION GET_INTERESTS(PARAM_USER_ID BIGINT)
RETURNS TABLE(INTEREST VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		STUDENT_INTERESTS.INTEREST
	FROM STUDENT_INTERESTS
	WHERE STUDENT_ID = PARAM_USER_ID;
END;
$$;