CREATE OR REPLACE FUNCTION INSERT_VIEW(PARAM_USER_ID BIGINT, PARAM_CONTENT_ID BIGINT)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
BEGIN
	INSERT INTO CONTENT_VIEWERS (USER_ID, CONTENT_ID)
	VALUES (PARAM_USER_ID, PARAM_CONTENT_ID);
	RETURN 0; --SUCCESS
EXCEPTION
	WHEN UNIQUE_VIOLATION THEN
		RETURN 1; --ALREADY VIEWED
END;
$$;