CREATE OR REPLACE FUNCTION INSERT_COURSE(PARAM_TEACHER_ID BIGINT, PARAM_COURSE_TITLE VARCHAR, PARAM_COURSE_DESCRIPTION VARCHAR, PARAM_COURSE_PRICE VARCHAR)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	NEW_COURSE_ID BIGINT;
	NEW_COURSE_PRICE INT;
BEGIN
	IF LENGTH(PARAM_COURSE_TITLE) = 0 THEN
		RETURN 1; --EMPTY COURSE TITLE ERROR
	END IF;
	IF LENGTH(PARAM_COURSE_PRICE) = 0 THEN
		NEW_COURSE_PRICE := 0;
	ELSE
		NEW_COURSE_PRICE := PARAM_COURSE_PRICE::INT;
	END IF;
	NEW_COURSE_ID = GET_NEW_COURSE_ID();
	INSERT INTO COURSES
	(COURSE_ID, TITLE, DESCRIPTION, PRICE, CREATOR_ID)
	VALUES(NEW_COURSE_ID, PARAM_COURSE_TITLE, PARAM_COURSE_DESCRIPTION, NEW_COURSE_PRICE, PARAM_TEACHER_ID);
	RETURN 0; --SUCCESS
END;
$$;