CREATE OR REPLACE FUNCTION INSERT_CONTENT(PARAM_CONTENT_TYPE VARCHAR, PARAM_COURSE_ID BIGINT, PARAM_TITLE VARCHAR, PARAM_DESCRIPTION VARCHAR)
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	NEW_CONTENT_ID BIGINT;
BEGIN
	NEW_CONTENT_ID := GET_NEW_CONTENT_ID();
	INSERT INTO CONTENTS (CONTENT_ID, TITLE, DESCRIPTION, COURSE_ID, CONTENT_TYPE)
	VALUES (NEW_CONTENT_ID, PARAM_TITLE, PARAM_DESCRIPTION, PARAM_COURSE_ID, PARAM_CONTENT_TYPE);
	RETURN NEW_CONTENT_ID;
END;
$$;