CREATE OR REPLACE FUNCTION IS_VALID_DATE(PARAM_DAY INT, PARAM_MONTH INT, PARAM_YEAR INT)
RETURNS BOOL
LANGUAGE PLPGSQL
AS
$$
DECLARE
BEGIN
	IF PARAM_MONTH = 2 THEN
		IF IS_LEAP_YEAR(PARAM_YEAR) THEN
			RETURN PARAM_DAY <= 29;
		ELSE
			RETURN PARAM_DAY <= 28;
		END IF;
	END IF;
	IF PARAM_MONTH IN (4, 6, 9, 11) THEN
		RETURN PARAM_DAY <= 30;
	END IF;
	RETURN TRUE;
END;
$$;