CREATE OR REPLACE FUNCTION LOGIN(PARAM_EMAIL VARCHAR, PARAM_PASSWORD VARCHAR, PARAM_STUDENT BOOL)
RETURNS BIGINT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	FOUND_USER_ID BIGINT;
BEGIN
	IF PARAM_STUDENT THEN
		SELECT USERS.USER_ID INTO FOUND_USER_ID
		FROM USERS
		JOIN STUDENTS
		ON (USERS.USER_ID = STUDENTS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL;
	ELSE
		SELECT USERS.USER_ID INTO FOUND_USER_ID
		FROM USERS
		JOIN TEACHERS
		ON (USERS.USER_ID = TEACHERS.USER_ID)
		WHERE EMAIL = PARAM_EMAIL;
	END IF;
	IF FOUND_USER_ID IS NULL THEN
		RETURN -1; --EMAIL NOT FOUND
	END IF;
	SELECT USER_ID INTO FOUND_USER_ID
	FROM USERS
	WHERE EMAIL = PARAM_EMAIL AND SECURITY_KEY = PARAM_PASSWORD;
	IF FOUND_USER_ID IS NULL THEN
		RETURN -2; --PASSWORD NOT MATCHED
	END IF;
	RETURN FOUND_USER_ID; --SUCCESS
END;
$$;