CREATE OR REPLACE FUNCTION SEARCH_COURSES(PARAM_SEARCH_TERM VARCHAR)
RETURNS TABLE(COURSE_ID BIGINT, TITLE VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT COURSES.COURSE_ID, COURSES.TITLE
	FROM COURSES
	WHERE LOWER(COURSES.TITLE) LIKE CONCAT('%', LOWER(PARAM_SEARCH_TERM), '%');
END;
$$;