CREATE OR REPLACE FUNCTION SEARCH_VIDEO(PARAM_SEARCH_TERM VARCHAR)
RETURNS TABLE(CONTENT_ID BIGINT, TITLE VARCHAR, DESCRIPTION VARCHAR, RATE NUMERIC, DATE_OF_CREATION DATE, CONTENT_TYPE VARCHAR, VIEW_COUNT BIGINT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	RETURN QUERY SELECT
		CONTENTS.CONTENT_ID,
		CONTENTS.TITLE,
		TRIM(CONTENTS.DESCRIPTION)::VARCHAR,
		CONTENTS.RATE::NUMERIC(3, 2),
		CONTENTS.DATE_OF_CREATION,
		TRIM(CONTENTS.CONTENT_TYPE)::VARCHAR,
		CONTENTS.VIEW_COUNT
	FROM 
		CONTENTS
	WHERE
		CONTENTS.CONTENT_TYPE = 'PAGE' AND LOWER(CONTENTS.TITLE) LIKE CONCAT('%', LOWER(PARAM_SEARCH_TERM), '%');
END;
$$;