CREATE OR REPLACE FUNCTION UPDATE_VIDEO(PARAM_CONTENT_ID BIGINT, PARAM_TITLE VARCHAR, PARAM_DESCRIPTION VARCHAR)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	DUPLICATE_VIDEO_ID BIGINT;
	CONTENT_COURSE_ID BIGINT;
BEGIN
	SELECT COURSE_ID INTO CONTENT_COURSE_ID
	FROM CONTENTS
	WHERE CONTENT_ID = PARAM_CONTENT_ID;
	SELECT CONTENT_ID INTO DUPLICATE_VIDEO_ID
	FROM CONTENTS
	WHERE CONTENT_TYPE = 'VIDEO' AND TITLE = PARAM_TITLE AND COURSE_ID = CONTENT_COURSE_ID AND CONTENT_ID != PARAM_CONTENT_ID;
	IF DUPLICATE_VIDEO_ID IS NOT NULL THEN
		RETURN -1; --DUPLICATE NAME ERROR
	END IF;
	UPDATE CONTENTS
	SET
		TITLE = PARAM_TITLE,
		DESCRIPTION = PARAM_DESCRIPTION
	WHERE CONTENT_ID  = PARAM_CONTENT_ID;
	RETURN 0; --SUCCESS
END;
$$;