CREATE OR REPLACE FUNCTION UPDATE_PAGE(PARAM_CONTENT_ID BIGINT, PARAM_TITLE VARCHAR)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
DECLARE
	DUPLICATE_PAGE_ID BIGINT;
	CONTENT_COURSE_ID BIGINT;
BEGIN
	SELECT COURSE_ID INTO CONTENT_COURSE_ID
	FROM CONTENTS
	WHERE CONTENT_ID = PARAM_CONTENT_ID;
	SELECT CONTENT_ID INTO DUPLICATE_PAGE_ID
	FROM CONTENTS
	WHERE CONTENT_TYPE = 'PAGE' AND TITLE = PARAM_TITLE AND COURSE_ID = CONTENT_COURSE_ID AND CONTENT_ID != PARAM_CONTENT_ID;
	IF DUPLICATE_PAGE_ID IS NOT NULL THEN
		RETURN -1; --DUPLICATE NAME ERROR
	END IF;
	UPDATE CONTENTS
	SET
		TITLE = PARAM_TITLE
	WHERE CONTENT_ID  = PARAM_CONTENT_ID;
	RETURN 0; --SUCCESS
END;
$$;