CREATE OR REPLACE FUNCTION UPDATE_USER_DETAILS(PARAM_USER_ID BIGINT, PARAM_FULL_NAME VARCHAR, PARAM_EMAIL VARCHAR, PARAM_PASSWORD VARCHAR, PARAM_BIO VARCHAR, PARAM_DATE_OF_BIRTH VARCHAR)
RETURNS INT
LANGUAGE PLPGSQL
AS
$$
BEGIN
	IF LENGTH(PARAM_FULL_NAME) = 0 THEN
		RETURN 1; --EMPTY FULL NAME
	ELSIF LENGTH(PARAM_EMAIL) = 0 THEN
		RETURN 2; --EMPTY EMAIL
	ELSIF PARAM_EMAIL NOT LIKE '%_@_%.___' THEN
		RETURN 3; --INVALID EMAIL
	ELSIF LENGTH(PARAM_PASSWORD) < 8 THEN
		RETURN 4; --PASSWORD TOO SMALL
	ELSIF LENGTH(PARAM_PASSWORD) > 32 THEN
		RETURN 5; --PASSWORD TOO BIG
	END IF;
	UPDATE USERS
	SET FULL_NAME = PARAM_FULL_NAME,
		EMAIL = PARAM_EMAIL,
		SECURITY_KEY = PARAM_PASSWORD,
		BIO = PARAM_BIO,
		DATE_OF_BIRTH = TO_DATE(PARAM_DATE_OF_BIRTH, 'YYYY-MM-DD')
	WHERE USER_ID = PARAM_USER_ID;
	RETURN 0; --SUCCESS
END;
$$;