CREATE OR REPLACE FUNCTION CONTENTS_VIEW_COUNT_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
	NEW_VIEW_COUNT BIGINT;
	ID BIGINT;
BEGIN
	IF NEW.CONTENT_ID IS NOT NULL THEN
		ID := NEW.CONTENT_ID;
	ELSE
		ID := OLD.CONTENT_ID;
	END IF;
	SELECT COUNT(*) INTO NEW_VIEW_COUNT
	FROM CONTENT_VIEWERS
	WHERE CONTENT_ID = ID;
	UPDATE CONTENTS
	SET VIEW_COUNT = NEW_VIEW_COUNT
	WHERE CONTENT_ID = ID;
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER CONTENTS_VIEW_COUNT_TRIGGER
AFTER INSERT OR DELETE OR UPDATE
ON CONTENT_VIEWERS
FOR EACH ROW
EXECUTE PROCEDURE CONTENTS_VIEW_COUNT_TRIGGER();