CREATE OR REPLACE FUNCTION CONTENTS_RATE_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
	AVERAGE_RATE NUMERIC;
	ID BIGINT;
BEGIN
	IF NEW.CONTENT_ID IS NOT NULL THEN
		ID := NEW.CONTENT_ID;
	ELSE
		ID := OLD.CONTENT_ID;
	END IF;
	SELECT AVG(RATE) INTO AVERAGE_RATE
	FROM CONTENT_VIEWERS
	WHERE CONTENT_ID = ID AND RATE != 0;
	IF AVERAGE_RATE IS NULL THEN
		AVERAGE_RATE := 0;
	END IF;
	UPDATE CONTENTS
	SET RATE = AVERAGE_RATE
	WHERE CONTENT_ID = ID;
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER CONTENTS_RATE_TRIGGER
AFTER INSERT OR DELETE OR UPDATE
OF RATE
ON CONTENT_VIEWERS
FOR EACH ROW
EXECUTE PROCEDURE CONTENTS_RATE_TRIGGER();