CREATE OR REPLACE FUNCTION ENROLLED_COURSES_INSERT_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
	CONTENT_COUNT BIGINT;
BEGIN
	SELECT COUNT(*) INTO CONTENT_COUNT
	FROM CONTENTS
	WHERE COURSE_ID = NEW.COURSE_ID;
	INSERT INTO COURSE_REMAIN_CONTENTS(USER_ID, COURSE_ID, REMAIN_COUNT)
	VALUES
	(NEW.USER_ID, NEW.COURSE_ID, CONTENT_COUNT);
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER ENROLLED_COURSES_INSERT_TRIGGER
AFTER INSERT
ON ENROLLED_COURSES
FOR EACH ROW
EXECUTE PROCEDURE ENROLLED_COURSES_INSERT_TRIGGER();