CREATE OR REPLACE FUNCTION INSERT_USER_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
BEGIN
	IF NEW.USER_TYPE = 'STUDENT' THEN
		INSERT INTO STUDENTS
		(USER_ID)
		VALUES (NEW.USER_ID);
	ELSE
		INSERT INTO TEACHERS
		(USER_ID)
		VALUES (NEW.USER_ID);
	END IF;
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER INSERT_USER_TRIGGER
AFTER INSERT
ON USERS
FOR EACH ROW
EXECUTE PROCEDURE INSERT_USER_TRIGGER();