CREATE OR REPLACE FUNCTION QUESTION_RATE_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
	AVG_RATE NUMERIC;
	ID BIGINT;
BEGIN
	IF NEW.QUESTION_ID IS NOT NULL THEN
		ID := NEW.QUESTION_ID;
	ELSE
		ID := OLD.QUESTION_ID;
	END IF;
	SELECT AVG(RATE) INTO AVG_RATE
	FROM QUESTION_RATES
	WHERE QUESTION_ID = ID AND RATE != 0;
	IF AVG_RATE IS NULL THEN
		AVG_RATE := 0;
	END IF;
	UPDATE FORUM_QUESTIONS
	SET RATE = AVG_RATE
	WHERE QUESTION_ID = ID;
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER QUESTION_RATE_TRIGGER
AFTER INSERT OR DELETE OR UPDATE
OF RATE
ON QUESTION_RATES
FOR EACH ROW
EXECUTE PROCEDURE QUESTION_RATE_TRIGGER();