CREATE OR REPLACE FUNCTION TEACHERS_RATE_TRIGGER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
	AVERAGE_RATE NUMERIC;
	ID BIGINT;
BEGIN
	IF NEW.CREATOR_ID IS NOT NULL THEN
		ID := NEW.CREATOR_ID;
	ELSE
		ID := OLD.CREATOR_ID;
	END IF;
	SELECT AVG(RATE) INTO AVERAGE_RATE
	FROM COURSES
	WHERE CREATOR_ID = ID;
	IF AVERAGE_RATE IS NULL THEN
		AVERAGE_RATE := 0;
	END IF;
	UPDATE TEACHERS
	SET RATE = AVERAGE_RATE
	WHERE USER_ID = ID;
	RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER TEACHERS_RATE_TRIGGER
AFTER INSERT OR DELETE OR UPDATE
OF RATE
ON COURSES
FOR EACH ROW
EXECUTE PROCEDURE TEACHERS_RATE_TRIGGER();