CREATE OR REPLACE PROCEDURE COMPLETE_VIEW(PARAM_USER_ID BIGINT, PARAM_CONTENT_ID BIGINT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	UPDATE CONTENT_VIEWERS
	SET COMPLETED = TRUE
	WHERE USER_ID = PARAM_USER_ID AND CONTENT_ID = PARAM_CONTENT_ID;
END;
$$;