CREATE OR REPLACE PROCEDURE DELETE_SPECIALITY(PARAM_TEACHER_ID BIGINT, PARAM_SPECIALITY VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	DELETE FROM TEACHER_SPECIALITIES
	WHERE TEACHER_ID = PARAM_TEACHER_ID AND SPECIALITY = PARAM_SPECIALITY;
END;
$$;