CREATE OR REPLACE PROCEDURE ENROLL_STUDENT(PARAM_STUDENT_ID BIGINT, PARAM_COURSE_ID BIGINT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	INSERT INTO ENROLLED_COURSES
	(USER_ID, COURSE_ID)
	VALUES(PARAM_STUDENT_ID, PARAM_COURSE_ID);
END;
$$;