CREATE OR REPLACE PROCEDURE INSERT_SPECIALITY(PARAM_TEACHER_ID BIGINT, PARAM_SPECIALITY VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	INSERT INTO TEACHER_SPECIALITIES (TEACHER_ID, SPECIALITY)
	VALUES (PARAM_TEACHER_ID, PARAM_SPECIALITY);
END;
$$;