CREATE OR REPLACE PROCEDURE POST_COMMENT(PARAM_USER_ID BIGINT, PARAM_CONTENT_ID BIGINT, PARAM_DESCRIPTION VARCHAR)
LANGUAGE PLPGSQL
AS
$$
DECLARE
	NEW_COMMENT_ID BIGINT;
BEGIN
	NEW_COMMENT_ID := GET_NEW_COMMENT_ID();
	INSERT INTO COMMENTS (COMMENT_ID, CONTENT_ID, COMMENTER_ID, DESCRIPTION)
	VALUES
		(NEW_COMMENT_ID, PARAM_CONTENT_ID, PARAM_USER_ID, PARAM_DESCRIPTION);
END;
$$;