CREATE OR REPLACE PROCEDURE POST_ANSWER(PARAM_USER_ID BIGINT, PARAM_QUESTION_ID BIGINT, PARAM_ANSWER VARCHAR)
LANGUAGE PLPGSQL
AS
$$
DECLARE
	NEW_ANSWER_ID BIGINT;
BEGIN
	NEW_ANSWER_ID := GET_NEW_ANSWER_ID();
	INSERT INTO FORUM_ANSWERS (ANSWER_ID, QUESTION_ID, ANSWERER_ID, ANSWER)
	VALUES
		(NEW_ANSWER_ID, PARAM_QUESTION_ID, PARAM_USER_ID, PARAM_ANSWER);
END;
$$;