CREATE OR REPLACE PROCEDURE UPDATE_COURSE(PARAM_COURSE_ID BIGINT, PARAM_TITLE VARCHAR, PARAM_DESCRIPTION VARCHAR, PARAM_PRICE INT)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	UPDATE COURSES
	SET
		TITLE = PARAM_TITLE,
		DESCRIPTION = PARAM_DESCRIPTION,
		PRICE = PARAM_PRICE
	WHERE
		COURSE_ID = PARAM_COURSE_ID;
END;
$$;