CREATE OR REPLACE PROCEDURE UPDATE_COMMENT_RATE(PARAM_COMMENT_ID BIGINT, PARAM_RATE NUMERIC)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	UPDATE COMMENTS
	SET RATE = PARAM_RATE
	WHERE COMMENT_ID = PARAM_COMMENT_ID;
END;
$$;