CREATE OR REPLACE PROCEDURE UPDATE_COMMENT_RATE(PARAM_USER_ID BIGINT, PARAM_COMMENT_ID BIGINT, PARAM_RATE INT)
LANGUAGE PLPGSQL
AS
$$
DECLARE
	FOUND_RATE INT;
BEGIN
	SELECT RATE INTO FOUND_RATE
	FROM COMMENT_RATES
	WHERE USER_ID = PARAM_USER_ID AND COMMENT_ID = PARAM_COMMENT_ID;
	IF FOUND_RATE IS NULL THEN
		INSERT INTO COMMENT_RATES (USER_ID, COMMENT_ID, RATE)
		VALUES (PARAM_USER_ID, PARAM_COMMENT_ID, PARAM_RATE);
	ELSE
		UPDATE COMMENT_RATES
		SET RATE = PARAM_RATE
		WHERE USER_ID = PARAM_USER_ID AND COMMENT_ID = PARAM_COMMENT_ID;
	END IF;
END;
$$;