CREATE OR REPLACE PROCEDURE UPDATE_ANSWER_RATE(PARAM_USER_ID BIGINT, PARAM_ANSWER_ID BIGINT, PARAM_RATE INT)
LANGUAGE PLPGSQL
AS
$$
DECLARE
	FOUND_RATE INT;
BEGIN
	SELECT RATE INTO FOUND_RATE
	FROM ANSWER_RATES
	WHERE USER_ID = PARAM_USER_ID AND ANSWER_ID = PARAM_ANSWER_ID;
	IF FOUND_RATE IS NULL THEN
		INSERT INTO ANSWER_RATES (USER_ID, ANSWER_ID, RATE)
		VALUES (PARAM_USER_ID, PARAM_ANSWER_ID, PARAM_RATE);
	ELSE
		UPDATE ANSWER_RATES
		SET RATE = PARAM_RATE
		WHERE USER_ID = PARAM_USER_ID AND ANSWER_ID = PARAM_ANSWER_ID;
	END IF;
END;
$$;