CREATE OR REPLACE PROCEDURE UPDATE_COMMENT(PARAM_COMMENT_ID BIGINT, PARAM_DESCRIPTION VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	UPDATE COMMENTS
	SET DESCRIPTION = PARAM_DESCRIPTION
	WHERE COMMENT_ID = PARAM_COMMENT_ID;
END;
$$;