CREATE OR REPLACE PROCEDURE UPDATE_ANSWER(PARAM_ANSWER_ID BIGINT, PARAM_ANSWER VARCHAR)
LANGUAGE PLPGSQL
AS
$$
BEGIN
	UPDATE FORUM_ANSWERS
	SET ANSWER = PARAM_ANSWER
	WHERE ANSWER_ID = PARAM_ANSWER_ID;
END;
$$;