#pragma once

#include "root/GetUserDetails.h"
#include "root/GetUserId.h"
#include "root/GetCoursesPopular.h"
#include "root/GetCourseDetails.h"
#include "root/GetCourseContents.h"
#include "root/GetContentDetails.h"
#include "root/GetComments.h"
#include "root/GetStudentDetails.h"
#include "root/GetCoursesStudent.h"
#include "root/GetCourseRemainContentCount.h"
#include "root/CheckStudentEnrolled.h"
#include "root/BuyCourse.h"
#include "root/GetCoursesTeacher.h"